server:
  http_port: 8080

db:
  host: "shorterDB"
  port: 5432
  schema: "public"
  database: "shorterUrl"
  username: "shorterUser"
  password: "shorterPass"


redis:
  host: "shorter-cache"
  port: 6379
  DB: 0
  ttl: 1