services:
  postgres:
    image: postgres:latest
    container_name: shorterDB
    environment:
      POSTGRES_USER: shorterUser
      POSTGRES_PASSWORD: shorterPass
      POSTGRES_DB: shorterUrl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shorterUser -d shorterUrl" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data: