services:
  postgres:
    image: postgres:latest
    container_name: shorterDB
    environment:
      POSTGRES_USER: shorterUser
      POSTGRES_PASSWORD: shorterPass
      POSTGRES_DB: shorterUrl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shorterUser -d shorterUrl" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    container_name: shorter-cache
    ports:
      - '6379:6379'
    restart: always
    command: >
      --databases 1
      --maxmemory-policy volatile-lru
      --appendonly no
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  app:
    container_name: shortner-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
volumes:
  postgres_data: